name: Manual Playwright Tests
on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Який хост використовувати? (напр. https://www.wikipedia.org)'
        required: true
        default: 'https://www.wikipedia.org'
      browser:
        description: 'Браузер для тестування'
        required: true
        type: choice
        options:
          - chromium
          - firefox
          - webkit
        default: 'chromium'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      env: cicd
      host: ${{ github.event.inputs.host }}
    steps:
    - uses: actions/checkout@v4

    # - name: Debug env
    #   run: echo "Поточне значення env — ${{ env.env }}"

    # - name: Debug host
    #   run: echo "Поточне значення env — ${{ github.event.inputs.host }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run Pytest with arguments
      run: |
        pytest -v
